name: MyCA

#trigger
on: [push]
 
  



# jobs
jobs: 
  #job name
  my-workflow-workshop:
    #OS that this workflow will be runnning on
    runs-on: ubuntu-latest
      

    #list of steps to perform task
    steps: 
    - name: echo current branch
      run: echo "$(date) Current branch is ${{ github.ref_name}}"
    - name: Checkout correct branch
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}
    - name: Testing
      run: echo ${{secrets.TESTING}}
    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with: 
        status: ${{job.status}}
        steps: ${{toJson(steps)}}
        channel: '#test-submission'
      if: always()
      env: 
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK