name: MyCA

#trigger
on: 
  push:
    branches:
      - "v[0-9]+.[0-9]"
  
# jobs
jobs: 
  #job name
  my-workflow-workshop:
    #OS that this workflow will be runnning on
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, '#NORUN')}}
      

    #list of steps to perform task
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 16 from the only
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Installing Railway package
      run: npm i -g @railway/cli

    - name: Deployment myRailway
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 

    - name: echo current branch
      run: echo "$(date) Current branch is ${{ github.ref_name}}"
      
    - name: Checkout my branch v0.1
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}
     
    

    - name: Create My Third Release
      uses: ncipollo/release-action@v1.11.1
      with: 
        tag: ${{ github.ref_name}}
        commit: ${{github.ref_name}}
        token: ${{secrets.MY_GITHUB_TOKEN}}
      

    - name: Testing
      run: echo ${{secrets.TESTING}}
    

    - name: Slack Notification From Long
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with: 
        channel-id: 'CHANNEL_ID'
        payload: |
          {
          
          "blocks": [
            {
              "type": "header",
              "text":{
                "type": "plain_text",
                "text": "DipSA55 CI/CD Assignment Submission",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Name:*\nXUJINLONG"
                },
                {
                  "type":"mrkdwn",
                  "text": "*Metriculation:*\nA0265066B"
                }
              ]
            },
            {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "*Email:*\nE1045741@u.nus.edu"
              },
              {
                "type": "mrkdwn",
                "text": "*Repostory:*\n<${{secrets.MY_GITHUB_URL}}"
              }
            ]
            },
            {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "*Deployment:*\n<${{secrets.MY_RAILWAY_URL}}>"
              }
            ]
            },
            {
            "type": "section",
            "fields":[
              {
                "type": "mrkdwn",
                "text": "<${{secrets.MY_RAILWAY_URL}} | Open Application>"
              }
            ]
            }
            
          ]
          }
          
      env: 
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        